services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      VERSION: "1.18.2"    # Cambia a la versión deseada
      TYPE: "FORGE" 
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - ./mods:/mods  
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}





 